"""Reusable service adapters for personal Agent projects."""

__version__ = "0.1.0"

from .chat import (
    ChatChoice,
    ChatMessage,
    ChatProvider,
    ChatRequest,
    ChatResponse,
    ChatService,
    ChatServiceError,
    ChatUsage,
    GenerateChat,
    MinimaxChat,
    OpenaiChat,
)
from .image import (
    GeneratedImage,
    GenerateImage,
    ImageGenerationError,
    ImageProvider,
    ImageRequest,
    ImageResponse,
    ImageService,
    MinimaxImage,
    OpenaiImage,
)
from .tts import (
    AudioSetting,
    ClonePrompt,
    DeleteVoiceResponse,
    GenerateSpeech,
    MinimaxSpeech,
    SpeechProvider,
    SpeechRequest,
    SpeechResponse,
    SpeechService,
    SynthesizedAudio,
    TimbreWeight,
    TtsServiceError,
    UploadCloneAudioRequest,
    UploadCloneAudioResponse,
    UploadedFile,
    VoiceCloneRequest,
    VoiceCloneResponse,
    VoiceInfo,
    VoiceListResponse,
    VoiceSetting,
)

__all__ = [
    "AudioSetting",
    "ChatChoice",
    "ChatMessage",
    "ChatProvider",
    "ChatRequest",
    "ChatResponse",
    "ChatService",
    "ChatServiceError",
    "ChatUsage",
    "ClonePrompt",
    "DeleteVoiceResponse",
    "GeneratedImage",
    "GenerateChat",
    "GenerateImage",
    "GenerateSpeech",
    "ImageGenerationError",
    "ImageProvider",
    "ImageRequest",
    "ImageResponse",
    "ImageService",
    "MinimaxChat",
    "MinimaxImage",
    "MinimaxSpeech",
    "OpenaiChat",
    "OpenaiImage",
    "SpeechProvider",
    "SpeechRequest",
    "SpeechResponse",
    "SpeechService",
    "SynthesizedAudio",
    "TimbreWeight",
    "TtsServiceError",
    "UploadCloneAudioRequest",
    "UploadCloneAudioResponse",
    "UploadedFile",
    "VoiceCloneRequest",
    "VoiceCloneResponse",
    "VoiceInfo",
    "VoiceListResponse",
    "VoiceSetting",
    "__version__",
]
