from .base import (
    AudioSetting,
    ClonePrompt,
    DeleteVoiceResponse,
    GenerateSpeech,
    SpeechRequest,
    SpeechResponse,
    SynthesizedAudio,
    TimbreWeight,
    TtsServiceError,
    UploadCloneAudioRequest,
    UploadCloneAudioResponse,
    UploadedFile,
    VoiceCloneRequest,
    VoiceCloneResponse,
    VoiceInfo,
    VoiceListResponse,
    VoiceSetting,
)
from .minimax import MinimaxSpeech
from .service import SpeechProvider, SpeechService

__all__ = [
    "AudioSetting",
    "ClonePrompt",
    "DeleteVoiceResponse",
    "GenerateSpeech",
    "MinimaxSpeech",
    "SpeechProvider",
    "SpeechRequest",
    "SpeechResponse",
    "SpeechService",
    "SynthesizedAudio",
    "TimbreWeight",
    "TtsServiceError",
    "UploadCloneAudioRequest",
    "UploadCloneAudioResponse",
    "UploadedFile",
    "VoiceCloneRequest",
    "VoiceCloneResponse",
    "VoiceInfo",
    "VoiceListResponse",
    "VoiceSetting",
]
